services:
  - type: web
    name: techsyzone
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/data
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
